In [1]:
# standardization(create)
from sklearn.preprocessing import StandardScaler
import numpy as np
x=np.array([[85,72,80],[130,14,151],[67,48,29],[100,11,102]])
Standard_Scaler=StandardScaler()
Standard_Scaler.fit(x)
x_new=Standard_Scaler.transform(x)
print("new data:",x_new)

new data: [[-0.45469886  1.41625815 -0.23955065]
 [ 1.49401055 -0.88144738  1.38026805]
 [-1.23418262  0.46548345 -1.4030824 ]
 [ 0.19487094 -1.00029422  0.262365  ]]


In [2]:
# minmaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
data=[[12,14,16],
        [6,8,10],
        [3,5,7],
        [6,1,9]]
scaler.fit(data)
scaled_data=scaler.transform(data)
scaled_data=scaler.fit_transform(data)
print(scaled_data)

[[1.         1.         1.        ]
 [0.33333333 0.53846154 0.33333333]
 [0.         0.30769231 0.        ]
 [0.33333333 0.         0.22222222]]


In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
df=pd.read_csv('bike_dataset.csv')
df.head()

model_name   price  CC  mileage   type_of_bike  weight_in_kg  \
0  Gravton Motors Quanta   99000 NaN    320.0  Electric Bike           100   
1      Simple Energy One  109999 NaN    236.0  Electric Bike           110   
2          Okaya Classiq   69900 NaN    200.0  Electric Bike            95   
3     Oben Electric Rorr  102999 NaN    200.0  Electric Bike           120   
4        Ola Electric S1   85099 NaN    181.0  Electric Bike           121   

                                               links  acceleration_speed  \
0  https://www.carandbike.com/gravton-motors-bike...                 4.2   
1  https://www.carandbike.com/simple-energy-bikes...                 3.6   
2     https://www.carandbike.com/okaya-bikes/classiq                 NaN   
3  https://www.carandbike.com/oben-electric-bikes...                 3.0   
4   https://www.carandbike.com/ola-electric-bikes/s1                 2.9   

   top_speed  
0       70.0  
1      100.0  
2       25.0  
3      100.0  
4      116.0

In [4]:
df.info()
df.dropna(subset=['acceleration_speed'],axis=0,inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   model_name          361 non-null    object 
 1   price               361 non-null    int64  
 2   CC                  304 non-null    float64
 3   mileage             361 non-null    float64
 4   type_of_bike        361 non-null    object 
 5   weight_in_kg        361 non-null    int64  
 6   links               361 non-null    object 
 7   acceleration_speed  170 non-null    float64
 8   top_speed           200 non-null    float64
dtypes: float64(4), int64(2), object(3)
memory usage: 25.5+ KB


In [5]:
# minimaxscaler
from sklearn.preprocessing import MinMaxScaler
Scaler=MinMaxScaler()
numeric_cols=['price','mileage','weight_in_kg','acceleration_speed','top_speed']
df[numeric_cols]=Scaler.fit_transform(df[numeric_cols])
df.head()

model_name     price  CC   mileage   type_of_bike  weight_in_kg  \
0  Gravton Motors Quanta  0.060999 NaN  1.000000  Electric Bike      0.186747   
1      Simple Energy One  0.072526 NaN  0.714771  Electric Bike      0.246988   
3     Oben Electric Rorr  0.065190 NaN  0.592530  Electric Bike      0.307229   
4        Ola Electric S1  0.046431 NaN  0.528014  Electric Bike      0.313253   
5    Ola Electric S1 Pro  0.083163 NaN  0.528014  Electric Bike      0.337349   

                                               links  acceleration_speed  \
0  https://www.carandbike.com/gravton-motors-bike...            0.249414   
1  https://www.carandbike.com/simple-energy-bikes...            0.202502   
3  https://www.carandbike.com/oben-electric-bikes...            0.155590   
4   https://www.carandbike.com/ola-electric-bikes/s1            0.147772   
5  https://www.carandbike.com/ola-electric-bikes/...            0.147772   

   top_speed  
0   0.177215  
1   0.367089  
3   0.367089  
4   0.468354  
5   0.468354

In [6]:
slr=MinMaxScaler()
numeric_cols=['price','mileage','weight_in_kg','acceleration_speed','top_speed']
scaled_data=scaler.fit_transform(df[numeric_cols])
scaled_df=pd.DataFrame(scaled_data,columns=numeric_cols)
df.head()

model_name     price  CC   mileage   type_of_bike  weight_in_kg  \
0  Gravton Motors Quanta  0.060999 NaN  1.000000  Electric Bike      0.186747   
1      Simple Energy One  0.072526 NaN  0.714771  Electric Bike      0.246988   
3     Oben Electric Rorr  0.065190 NaN  0.592530  Electric Bike      0.307229   
4        Ola Electric S1  0.046431 NaN  0.528014  Electric Bike      0.313253   
5    Ola Electric S1 Pro  0.083163 NaN  0.528014  Electric Bike      0.337349   

                                               links  acceleration_speed  \
0  https://www.carandbike.com/gravton-motors-bike...            0.249414   
1  https://www.carandbike.com/simple-energy-bikes...            0.202502   
3  https://www.carandbike.com/oben-electric-bikes...            0.155590   
4   https://www.carandbike.com/ola-electric-bikes/s1            0.147772   
5  https://www.carandbike.com/ola-electric-bikes/...            0.147772   

   top_speed  
0   0.177215  
1   0.367089  
3   0.367089  
4   0.468354  
5   0.468354

In [10]:
# normalization
from sklearn.preprocessing import Normalizer
scaler=Normalizer()
numeric_cols=['price','mileage','weight_in_kg','acceleration_speed','top_speed']
df[numeric_cols]=scaler.fit_transform(df[numeric_cols])
df.head()

model_name     price  CC   mileage   type_of_bike  weight_in_kg  \
0  Gravton Motors Quanta  0.057327 NaN  0.939803  Electric Bike      0.175505   
1      Simple Energy One  0.083583 NaN  0.823743  Electric Bike      0.284643   
3     Oben Electric Rorr  0.083557 NaN  0.759470  Electric Bike      0.393788   
4        Ola Electric S1  0.058955 NaN  0.670430  Electric Bike      0.397744   
5    Ola Electric S1 Pro  0.103896 NaN  0.659650  Electric Bike      0.421453   

                                               links  acceleration_speed  \
0  https://www.carandbike.com/gravton-motors-bike...            0.234400   
1  https://www.carandbike.com/simple-energy-bikes...            0.233375   
3  https://www.carandbike.com/oben-electric-bikes...            0.199427   
4   https://www.carandbike.com/ola-electric-bikes/s1            0.187629   
5  https://www.carandbike.com/ola-electric-bikes/...            0.184612   

   top_speed  
0   0.166547  
1   0.423054  
3   0.470513  
4   0.594679  
5   0.585118

In [14]:
# standardization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
numeric_cols=['price','mileage','weight_in_kg','acceleration_speed','top_speed']
df[numeric_cols]=scaler.fit_transform(df[numeric_cols])
df.head()

model_name     price  CC   mileage   type_of_bike  weight_in_kg  \
0  Gravton Motors Quanta -0.739033 NaN  3.612288  Electric Bike     -2.076952   
1      Simple Energy One -0.468280 NaN  3.050407  Electric Bike     -1.455804   
3     Oben Electric Rorr -0.468551 NaN  2.739243  Electric Bike     -0.834616   
4        Ola Electric S1 -0.722252 NaN  2.308170  Electric Bike     -0.812103   
5    Ola Electric S1 Pro -0.258811 NaN  2.255984  Electric Bike     -0.677167   

                                               links  acceleration_speed  \
0  https://www.carandbike.com/gravton-motors-bike...           -0.501792   
1  https://www.carandbike.com/simple-energy-bikes...           -0.505569   
3  https://www.carandbike.com/oben-electric-bikes...           -0.630709   
4   https://www.carandbike.com/ola-electric-bikes/s1           -0.674198   
5  https://www.carandbike.com/ola-electric-bikes/...           -0.685318   

   top_speed  
0  -2.022941  
1  -0.725418  
3  -0.485350  
4   0.142737  
5   0.094371